add Artifacts scanning

diff --git a/.github/workflows/aqua-sbom.yml b/.github/workflows/aqua-sbom.yml
--- a/.github/workflows/aqua-sbom.yml
+++ b/.github/workflows/aqua-sbom.yml
@@ -27,3 +27,32 @@ jobs:
           # Set these two ONLY if your Aqua env is not US:
           AQUA_URL: https://api.asia-1.supply-chain.cloud.aquasec.com
           CSPM_URL: https://asia-1.api.cloudsploit.com
+
+      # Step 3: Release Artifact Mapping using Billy
+      - name: Manifest Generation (Billy)
+        run: |
+          export BILLY_SERVER=https://billy.asia-1.codesec.aquasec.com
+
+          # Download Billy installer
+          curl -sLo install.sh https://download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+
+          # Verify checksum
+          if ! cat install.sh.checksum | sha256sum --check; then
+            echo "install.sh checksum failed"
+            exit 1
+          fi
+
+          # Install Billy in current directory
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+
+          # Run Billy to generate Release Artifact mapping
+          ./billy generate \
+            --access-token "${{ github.token }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --cspm-url "https://asia-1.api.cloudsploit.com" \
+            --artifact-path "node:18"
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
